### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by KC-software-en** [KC-software-en/QuizMe#76]
Dockerise the project

**Comment by deviserops** [comment]
Hello @KC-software-en 

Can you describe the issue in details.

Do you want to run this project on local with dockerized environment or to complete dockerized the project and deploy to docker hub.

Local dockerized will only use for development purpose, and complete dockerized will be will use for deployment with CI/CD (If need be.)

**Comment by KC-software-en** [comment]
Hi @deviserops 

The intent is to add it to the Docker Hub repo for the kcse1 account. QuizMe requires the creation of a file - Dockerfile

**Comment by deviserops** [comment]
@KC-software-en 
I have created a PR for this Please check. #80
